### ISSUE TITLE
[EPIC] PS4

### ISSUE THREAD

**Issue by mrteera** [mrteera/web16-06#25]
- [x] Structure planning (google docs)
- [x] User data model #26
- [x] User registration, management page flow sketch #27
- [x] User registration and login pages implementation #28
- [x] User admin pages #29
- [x] Application audit for sensitive data #30
- [x] How to avoid SQL Injection and XSS attacks #31
- [x] SSL #32

**Comment by mrteera** [comment]
Admin
http://activeadmin.info/
https://github.com/sferik/rails_admin
